"""USDA-NRCS SSURGO soil-survey screening utilities.

The module queries the official Soil Data Access (SDA) REST service. Map-unit
polygons are intersected with the requested WGS84 point-buffer ROI inside SDA,
while component, restriction, and horizon attributes are joined by SSURGO keys.
The resulting indicators are screening evidence, not site-specific measurements.

Service documentation:
  https://sdmdataaccess.sc.egov.usda.gov/WebServiceHelp.aspx
"""

from __future__ import annotations

import logging
import math
from collections import defaultdict
from datetime import datetime, timezone
from typing import Any

from nepa_mcp_common.arcgis import ArcGISService
from nepa_mcp_common.http import UpstreamServiceError, post_json
from nepa_mcp_common.spatial import (
    ClippedAreaResult,
    SpatialAreaStatus,
    SpatialGeometryError,
    clipped_union_area_from_esri_geometries,
    esri_polygon_to_wgs84_wkt,
)
from nepa_mcp_common.validation import validate_coordinates
from src.core.constants import (
    MAX_COMPONENT_ROWS,
    MAX_DETAIL_MAPUNITS,
    MAX_MAPUNITS,
    SDA_HELP_URL,
    SDA_POST_URL,
    SDA_TIMEOUT_SECONDS,
    WEB_SOIL_SURVEY_URL,
)

logger = logging.getLogger(__name__)

SQ_METERS_PER_ACRE = 4046.8564224
SOIL_SCREENING_BOUNDARY = (
    "Soil-survey screening only — not geotechnical advice, a site-specific drainage or infiltration study, "
    "a wetland delineation, or an agency farmland determination."
)


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _coerce_text(value: Any, *, default: str = "") -> str:
    if value is None:
        return default
    text = str(value).strip()
    return text or default


def _coerce_float(value: Any) -> float | None:
    try:
        number = float(value)
    except (TypeError, ValueError, OverflowError):
        return None
    return number if math.isfinite(number) else None


def _table_rows(payload: dict[str, Any], table_name: str) -> list[dict[str, Any]]:
    """Convert one SDA JSON+COLUMNNAME table into dictionaries."""
    table = payload.get(table_name)
    if table is None:
        return []
    if not isinstance(table, list) or not table:
        raise UpstreamServiceError(f"USDA-NRCS Soil Data Access returned malformed {table_name} data")

    header = table[0]
    if not isinstance(header, list) or not header or not all(isinstance(column, str) for column in header):
        raise UpstreamServiceError(f"USDA-NRCS Soil Data Access returned malformed {table_name} columns")
    if len(set(header)) != len(header):
        raise UpstreamServiceError(f"USDA-NRCS Soil Data Access returned duplicate {table_name} columns")

    rows: list[dict[str, Any]] = []
    for values in table[1:]:
        if not isinstance(values, list) or len(values) != len(header):
            raise UpstreamServiceError(f"USDA-NRCS Soil Data Access returned malformed {table_name} rows")
        rows.append(dict(zip(header, values, strict=True)))
    return rows


def _post_sda_query(query: str) -> dict[str, Any]:
    """Run one fixed-shape SDA query and return its JSON tables."""
    return post_json(
        SDA_POST_URL,
        json_body={"query": query, "format": "JSON+COLUMNNAME"},
        timeout=SDA_TIMEOUT_SECONDS,
        service_name="USDA-NRCS Soil Data Access",
    )


def _safe_wkt(wkt: str) -> str:
    """Reject characters outside the WKT generated by the shared geometry helper."""
    if not wkt or "'" in wkt or ";" in wkt or "--" in wkt:
        raise ValueError("ROI geometry could not be serialized safely for Soil Data Access")
    return wkt


def _mapunit_query(wkt: str) -> str:
    safe_wkt = _safe_wkt(wkt)
    aoi = f"geometry::STGeomFromText('{safe_wkt}',4326).MakeValid()"
    return f"""
WITH aoi AS (SELECT {aoi} AS geom)
SELECT TOP {MAX_MAPUNITS + 1}
    mu.mukey,
    mu.musym,
    mu.muname,
    mu.farmlndcl,
    l.areasymbol,
    sac.saverest,
    SUM(
        geography::STGeomFromWKB(
            mp.mupolygongeo.STIntersection(aoi.geom).STAsBinary(),4326
        ).STArea()
    ) AS area_sqm
FROM mupolygon AS mp
CROSS JOIN aoi
INNER JOIN mapunit AS mu ON mu.mukey = mp.mukey
INNER JOIN legend AS l ON l.lkey = mu.lkey
LEFT JOIN sacatalog AS sac ON sac.areasymbol = l.areasymbol
WHERE mp.mupolygongeo.STIntersects(aoi.geom) = 1
GROUP BY mu.mukey, mu.musym, mu.muname, mu.farmlndcl, l.areasymbol, sac.saverest
ORDER BY area_sqm DESC, mu.mukey
""".strip()


def _constraint_queries(mapunit_keys: list[str]) -> tuple[str, str, str]:
    """Build bounded component, restriction, and horizon queries from trusted keys."""
    if not mapunit_keys:
        raise ValueError("At least one map-unit key is required")
    if len(mapunit_keys) > MAX_MAPUNITS:
        raise ValueError(f"At most {MAX_MAPUNITS} map-unit keys are supported")
    if any(not key.isascii() or not key.isdigit() for key in mapunit_keys):
        raise ValueError("Map-unit keys must contain ASCII digits only")

    key_list = ",".join(mapunit_keys)
    component_keys = f"SELECT cokey FROM component WHERE mukey IN ({key_list})"
    component_query = f"""
SELECT TOP {MAX_COMPONENT_ROWS + 1}
    mukey, cokey, compname, comppct_r, majcompflag, hydgrp, drainagecl, slope_r
FROM component
WHERE mukey IN ({key_list})
ORDER BY mukey, comppct_r DESC, cokey
""".strip()
    restriction_query = f"""
SELECT TOP {MAX_COMPONENT_ROWS + 1}
    cokey, reskind, resdept_l, resdept_r, resdept_h
FROM corestrictions
WHERE cokey IN ({component_keys})
ORDER BY cokey, resdept_r, reskind
""".strip()
    horizon_query = f"""
SELECT TOP {MAX_COMPONENT_ROWS + 1}
    cokey, chkey, hzname, hzdept_r, hzdepb_r, kffact, kwfact
FROM chorizon
WHERE cokey IN ({component_keys}) AND hzdept_r < 50
ORDER BY cokey, hzdept_r, chkey
""".strip()
    return component_query, restriction_query, horizon_query


def _unavailable_result(lat: float, lon: float, buffer_miles: float, message: str) -> dict[str, Any]:
    return {
        "center": {"latitude": lat, "longitude": lon},
        "buffer_miles": buffer_miles,
        "retrieved_at": _utc_now(),
        "roi_area_acres": None,
        "mapped_area_acres": None,
        "coverage_pct": None,
        "mapunit_count": 0,
        "mapunits": [],
        "warnings": [message],
        "truncated": False,
        "partial": False,
        "data_unavailable": True,
        "error": message,
    }


def get_soil_mapunits_in_roi(lat: float, lon: float, buffer_miles: float = 1.0) -> dict[str, Any]:
    """Return SSURGO map units and clipped acreage inside a point-buffer ROI."""
    lat, lon, buffer_miles = validate_coordinates(lat, lon, buffer_miles, max_distance_miles=10.0)

    try:
        roi_geometry = ArcGISService.create_roi_buffer(lat, lon, buffer_miles)
        roi_wkt = esri_polygon_to_wgs84_wkt(roi_geometry)
        roi_area: ClippedAreaResult = clipped_union_area_from_esri_geometries([roi_geometry], roi_geometry)
        if roi_area.status is not SpatialAreaStatus.OK or roi_area.area_square_meters is None:
            raise SpatialGeometryError("ROI area could not be calculated")
    except (ValueError, SpatialGeometryError, UpstreamServiceError, RuntimeError) as exc:
        logger.error("NRCS soils ROI creation failed: %s", exc)
        return _unavailable_result(
            lat,
            lon,
            buffer_miles,
            "ROI geometry was unavailable for the NRCS SSURGO request; results are unavailable, not a no-hit finding.",
        )

    try:
        payload = _post_sda_query(_mapunit_query(roi_wkt))
        raw_mapunits = _table_rows(payload, "Table")
    except (UpstreamServiceError, ValueError) as exc:
        logger.error("NRCS Soil Data Access map-unit query failed: %s", exc)
        return _unavailable_result(
            lat,
            lon,
            buffer_miles,
            "USDA-NRCS Soil Data Access was unavailable for this request; results are unavailable, not a no-hit finding.",
        )

    roi_area_sqm = roi_area.area_square_meters

    warnings: list[str] = []
    mapunits: list[dict[str, Any]] = []
    skipped = 0
    truncated = len(raw_mapunits) > MAX_MAPUNITS
    for row in raw_mapunits[:MAX_MAPUNITS]:
        mukey = _coerce_text(row.get("mukey"))
        area_sqm = _coerce_float(row.get("area_sqm"))
        if not mukey.isascii() or not mukey.isdigit() or area_sqm is None or area_sqm < 0:
            skipped += 1
            continue
        area_acres = area_sqm / SQ_METERS_PER_ACRE
        mapunits.append(
            {
                "mukey": mukey,
                "symbol": _coerce_text(row.get("musym"), default="Unknown"),
                "name": _coerce_text(row.get("muname"), default="Unknown"),
                "farmland_classification": _coerce_text(row.get("farmlndcl"), default="Not rated or not available"),
                "survey_area_symbol": _coerce_text(row.get("areasymbol"), default="Unknown"),
                "survey_version_date": _coerce_text(row.get("saverest"), default="Unknown"),
                "area_square_meters": area_sqm,
                "area_acres": round(area_acres, 2),
                "roi_percentage": round(area_sqm / roi_area_sqm * 100.0, 2),
            }
        )

    if truncated:
        warnings.append(
            f"The ROI intersected more than {MAX_MAPUNITS} SSURGO map units; results were capped and are partial."
        )
    if skipped:
        warnings.append(
            f"Skipped {skipped} malformed SSURGO map-unit record{'s' if skipped != 1 else ''}; results are partial."
        )

    mapped_area_sqm = sum(item["area_square_meters"] for item in mapunits)
    raw_coverage_pct = mapped_area_sqm / roi_area_sqm * 100.0
    if raw_coverage_pct > 100.5:
        warnings.append(
            "Summed SSURGO intersections exceeded the ROI area, indicating overlapping source polygons; "
            "coverage is capped at 100 percent."
        )
    coverage_pct = min(100.0, raw_coverage_pct)
    if not mapunits:
        warnings.append(
            "No SSURGO map units were returned. This may indicate unmapped or unavailable soil-survey coverage, "
            "not an absence of soil constraints."
        )

    complete = not truncated and not skipped
    return {
        "center": {"latitude": lat, "longitude": lon},
        "buffer_miles": buffer_miles,
        "retrieved_at": _utc_now(),
        "roi_area_acres": round(roi_area_sqm / SQ_METERS_PER_ACRE, 2),
        "mapped_area_acres": round(mapped_area_sqm / SQ_METERS_PER_ACRE, 2),
        "unmapped_area_acres": (
            round(max(0.0, roi_area_sqm - mapped_area_sqm) / SQ_METERS_PER_ACRE, 2) if complete else None
        ),
        "coverage_pct": round(coverage_pct, 2),
        "mapunit_count": len(mapunits),
        "mapunits": mapunits,
        "warnings": warnings,
        "truncated": truncated,
        "partial": truncated or bool(skipped),
        "skipped_records": skipped,
        "data_unavailable": False,
    }


def _parse_constraint_rows(
    component_payload: dict[str, Any],
    restriction_payload: dict[str, Any],
    horizon_payload: dict[str, Any],
) -> tuple[list[dict[str, Any]], list[str], bool]:
    warnings: list[str] = []
    raw_components = _table_rows(component_payload, "Table")
    raw_restrictions = _table_rows(restriction_payload, "Table")
    raw_horizons = _table_rows(horizon_payload, "Table")
    truncated_tables = [
        name
        for name, rows in (
            ("component", raw_components),
            ("restriction", raw_restrictions),
            ("horizon", raw_horizons),
        )
        if len(rows) > MAX_COMPONENT_ROWS
    ]
    if truncated_tables:
        warnings.append(
            "SSURGO detail rows reached the safety cap for "
            + ", ".join(truncated_tables)
            + "; the constraint summary is partial."
        )

    restrictions_by_component: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for row in raw_restrictions[:MAX_COMPONENT_ROWS]:
        cokey = _coerce_text(row.get("cokey"))
        depth_r = _coerce_float(row.get("resdept_r"))
        if not cokey.isascii() or not cokey.isdigit():
            continue
        restrictions_by_component[cokey].append(
            {
                "kind": _coerce_text(row.get("reskind"), default="Unspecified restriction"),
                "depth_low_cm": _coerce_float(row.get("resdept_l")),
                "depth_representative_cm": depth_r,
                "depth_high_cm": _coerce_float(row.get("resdept_h")),
            }
        )

    horizons_by_component: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for row in raw_horizons[:MAX_COMPONENT_ROWS]:
        cokey = _coerce_text(row.get("cokey"))
        if not cokey.isascii() or not cokey.isdigit():
            continue
        horizons_by_component[cokey].append(
            {
                "horizon_key": _coerce_text(row.get("chkey")),
                "name": _coerce_text(row.get("hzname"), default="Unnamed horizon"),
                "top_depth_cm": _coerce_float(row.get("hzdept_r")),
                "bottom_depth_cm": _coerce_float(row.get("hzdepb_r")),
                "k_factor_fine_earth": _coerce_float(row.get("kffact")),
                "k_factor_whole_soil": _coerce_float(row.get("kwfact")),
            }
        )

    components: list[dict[str, Any]] = []
    skipped = 0
    for row in raw_components[:MAX_COMPONENT_ROWS]:
        mukey = _coerce_text(row.get("mukey"))
        cokey = _coerce_text(row.get("cokey"))
        component_pct = _coerce_float(row.get("comppct_r"))
        if not mukey.isascii() or not mukey.isdigit() or not cokey.isascii() or not cokey.isdigit():
            skipped += 1
            continue
        component_horizons = horizons_by_component.get(cokey, [])
        surface_horizon = next(
            (
                horizon
                for horizon in component_horizons
                if horizon["k_factor_fine_earth"] is not None or horizon["k_factor_whole_soil"] is not None
            ),
            None,
        )
        components.append(
            {
                "mukey": mukey,
                "cokey": cokey,
                "name": _coerce_text(row.get("compname"), default="Unknown component"),
                "component_percentage": component_pct,
                "major_component": _coerce_text(row.get("majcompflag")).casefold() == "yes",
                "hydrologic_group": _coerce_text(row.get("hydgrp"), default="Not rated"),
                "drainage_class": _coerce_text(row.get("drainagecl"), default="Not rated"),
                "representative_slope_pct": _coerce_float(row.get("slope_r")),
                "restrictions": restrictions_by_component.get(cokey, []),
                "surface_horizon": surface_horizon,
            }
        )

    if skipped:
        warnings.append(
            f"Skipped {skipped} malformed SSURGO component record{'s' if skipped != 1 else ''}; "
            "the constraint summary is partial."
        )
    return components, warnings, bool(truncated_tables or skipped)


def _weighted_distribution(
    mapunits_by_key: dict[str, dict[str, Any]],
    components: list[dict[str, Any]],
    field: str,
) -> dict[str, float]:
    weighted_acres: dict[str, float] = defaultdict(float)
    for component in components:
        value = _coerce_text(component.get(field), default="Not rated")
        component_pct = component.get("component_percentage")
        mapunit = mapunits_by_key.get(component["mukey"])
        if mapunit is None or component_pct is None:
            continue
        weighted_acres[value] += mapunit["area_acres"] * component_pct / 100.0
    return dict(sorted((key, round(value, 2)) for key, value in weighted_acres.items()))


def summarize_soil_constraints_for_siting(lat: float, lon: float, buffer_miles: float = 1.0) -> dict[str, Any]:
    """Combine map-unit, component, restriction, and horizon indicators for siting."""
    result = get_soil_mapunits_in_roi(lat, lon, buffer_miles)
    if result.get("data_unavailable") or not result["mapunits"]:
        result["components"] = []
        result["indicators"] = {}
        return result

    mapunit_keys = [item["mukey"] for item in result["mapunits"]]
    try:
        component_query, restriction_query, horizon_query = _constraint_queries(mapunit_keys)
        component_payload = _post_sda_query(component_query)
        restriction_payload = _post_sda_query(restriction_query)
        horizon_payload = _post_sda_query(horizon_query)
        components, warnings, partial = _parse_constraint_rows(
            component_payload,
            restriction_payload,
            horizon_payload,
        )
    except (UpstreamServiceError, ValueError) as exc:
        logger.error("NRCS Soil Data Access constraint query failed: %s", exc)
        result["warnings"].append(
            "SSURGO component, restriction, and horizon details were unavailable; the map-unit context remains usable."
        )
        result["partial"] = True
        result["components"] = []
        result["indicators"] = {}
        return result

    result["warnings"].extend(warnings)
    result["partial"] = result["partial"] or partial
    result["components"] = components

    mapunits_by_key = {item["mukey"]: item for item in result["mapunits"]}
    slopes = [
        component["representative_slope_pct"]
        for component in components
        if component["representative_slope_pct"] is not None
    ]
    restrictions = [
        {
            **restriction,
            "component": component["name"],
            "component_percentage": component["component_percentage"],
            "mukey": component["mukey"],
        }
        for component in components
        for restriction in component["restrictions"]
        if restriction["depth_representative_cm"] is not None
    ]
    kfactors = [
        component["surface_horizon"][field]
        for component in components
        if component["surface_horizon"] is not None
        for field in ("k_factor_fine_earth", "k_factor_whole_soil")
        if component["surface_horizon"][field] is not None
    ]
    farmland_acres: dict[str, float] = defaultdict(float)
    for mapunit in result["mapunits"]:
        farmland_acres[mapunit["farmland_classification"]] += mapunit["area_acres"]

    shallowest = min(restrictions, key=lambda item: item["depth_representative_cm"], default=None)
    steepest_component = max(
        (component for component in components if component["representative_slope_pct"] is not None),
        key=lambda item: item["representative_slope_pct"],
        default=None,
    )
    indicators = {
        "hydrologic_group_estimated_acres": _weighted_distribution(mapunits_by_key, components, "hydrologic_group"),
        "drainage_class_estimated_acres": _weighted_distribution(mapunits_by_key, components, "drainage_class"),
        "representative_slope_pct_min": min(slopes) if slopes else None,
        "representative_slope_pct_max": max(slopes) if slopes else None,
        "steepest_component": steepest_component,
        "shallowest_restriction": shallowest,
        "surface_k_factor_min": min(kfactors) if kfactors else None,
        "surface_k_factor_max": max(kfactors) if kfactors else None,
        "farmland_classification_acres": dict(
            sorted((classification, round(acres, 2)) for classification, acres in farmland_acres.items())
        ),
    }
    result["indicators"] = indicators
    return result


def get_farmland_classification_in_roi(lat: float, lon: float, buffer_miles: float = 1.0) -> dict[str, Any]:
    """Return exact SSURGO farmland classes summarized by clipped map-unit acreage."""
    result = get_soil_mapunits_in_roi(lat, lon, buffer_miles)
    classifications: dict[str, dict[str, Any]] = {}
    for mapunit in result["mapunits"]:
        classification = mapunit["farmland_classification"]
        item = classifications.setdefault(classification, {"area_acres": 0.0, "mapunit_count": 0})
        item["area_acres"] += mapunit["area_acres"]
        item["mapunit_count"] += 1

    roi_area = result.get("roi_area_acres")
    for item in classifications.values():
        item["area_acres"] = round(item["area_acres"], 2)
        item["roi_percentage"] = round(item["area_acres"] / roi_area * 100.0, 2) if roi_area else None
    result["classifications"] = dict(sorted(classifications.items()))
    return result


def _base_lines(data: dict[str, Any], title: str) -> list[str]:
    center = data["center"]
    lines = [
        title,
        "",
        f"Location: ({center['latitude']}, {center['longitude']})",
        f"Buffer: {data['buffer_miles']} miles",
        f"Retrieved: {data['retrieved_at']}",
    ]
    if data.get("roi_area_acres") is not None:
        lines.extend(
            [
                f"ROI Area: {data['roi_area_acres']:,.2f} acres",
                f"Mapped SSURGO Coverage: {data['mapped_area_acres']:,.2f} acres ({data['coverage_pct']:.2f}%)",
            ]
        )
    survey_versions = sorted(
        {
            (item["survey_area_symbol"], item["survey_version_date"])
            for item in data.get("mapunits", [])
            if item.get("survey_area_symbol")
        }
    )
    if survey_versions:
        lines.append("Survey Versions: " + "; ".join(f"{symbol}: {version}" for symbol, version in survey_versions))
    lines.append("")
    for warning in data.get("warnings", []):
        lines.append(f"Warning: {warning}")
    if data.get("warnings"):
        lines.append("")
    return lines


def _boundary_lines(*, farmland: bool = False) -> list[str]:
    lines = [
        "",
        "Data Source: USDA Natural Resources Conservation Service, Soil Survey Geographic Database (SSURGO), "
        "queried through Soil Data Access.",
        f"Source Documentation: {SDA_HELP_URL}",
        f"Web Soil Survey: {WEB_SOIL_SURVEY_URL}",
        f"Boundary: {SOIL_SCREENING_BOUNDARY}",
        "Note: Map-unit components and inclusions are not spatially located within a map-unit polygon; "
        "component percentages are estimates for the map unit, not parcel-specific measurements.",
    ]
    if farmland:
        lines.append(
            "Note: SSURGO farmland classification alone does not determine Farmland Protection Policy Act "
            "applicability, conversion acreage, exemptions, or an AD-1006 site-assessment score."
        )
    return lines


def format_soil_mapunits_summary(data: dict[str, Any], *, max_results: int = 50, result_offset: int = 0) -> str:
    """Format a bounded page of intersecting SSURGO map units."""
    lines = _base_lines(data, "NRCS SSURGO Soil Map Units")
    if data.get("data_unavailable"):
        lines.append(f"Status: Data unavailable — {data.get('error', 'unknown upstream error')}")
        return "\n".join(lines + _boundary_lines())

    mapunits = data.get("mapunits", [])
    total = len(mapunits)
    page = mapunits[result_offset : result_offset + max_results]
    if page:
        start = result_offset + 1
        end = result_offset + len(page)
        lines.append(f"Map Unit Details ({start}–{end} of {total}{'+' if data.get('truncated') else ''}):")
        for mapunit in page:
            lines.extend(
                [
                    f"- **{mapunit['symbol']} — {mapunit['name']}** (`mukey` {mapunit['mukey']})",
                    f"  - ROI intersection: {mapunit['area_acres']:,.2f} acres ({mapunit['roi_percentage']:.2f}%)",
                    f"  - Farmland classification: {mapunit['farmland_classification']}",
                    f"  - Survey area/version: {mapunit['survey_area_symbol']} / {mapunit['survey_version_date']}",
                ]
            )
        if end < total or data.get("truncated"):
            lines.append(f"Additional map units are not shown. Request a later result_offset up to {MAX_MAPUNITS - 1}.")
    else:
        lines.append("No SSURGO map units are available in this result window.")
    return "\n".join(lines + _boundary_lines())


def _format_distribution(values: dict[str, float], roi_area_acres: float | None) -> list[str]:
    if not values:
        return ["  Not rated or unavailable."]
    lines = []
    for label, acres in sorted(values.items(), key=lambda item: (-item[1], item[0])):
        percentage = acres / roi_area_acres * 100.0 if roi_area_acres else None
        if percentage is None:
            pct_text = ""
        elif 0 < percentage < 0.01:
            pct_text = "; less than 0.01% of ROI"
        else:
            pct_text = f"; approximately {percentage:.2f}% of ROI"
        lines.append(f"  {label}: {acres:,.2f} estimated acres{pct_text}")
    return lines


def format_soil_constraints_summary(data: dict[str, Any]) -> str:
    """Format transparent, non-scored SSURGO siting indicators."""
    lines = _base_lines(data, "NRCS SSURGO Soil Constraints Screening")
    if data.get("data_unavailable"):
        lines.append(f"Status: Data unavailable — {data.get('error', 'unknown upstream error')}")
        return "\n".join(lines + _boundary_lines(farmland=True))
    if not data.get("mapunits"):
        lines.append("No mapped SSURGO soil units were available for constraint screening.")
        return "\n".join(lines + _boundary_lines(farmland=True))

    indicators = data.get("indicators", {})
    if not indicators:
        lines.append("Component, restriction, and horizon indicators were unavailable for this request.")
        return "\n".join(lines + _boundary_lines(farmland=True))

    roi_area = data.get("roi_area_acres")
    lines.extend(["Hydrologic Soil Groups (component-weighted estimates):"])
    lines.extend(_format_distribution(indicators["hydrologic_group_estimated_acres"], roi_area))
    lines.extend(["", "Drainage Classes (component-weighted estimates):"])
    lines.extend(_format_distribution(indicators["drainage_class_estimated_acres"], roi_area))

    slope_min = indicators.get("representative_slope_pct_min")
    slope_max = indicators.get("representative_slope_pct_max")
    lines.extend(["", "Physical Indicators:"])
    if slope_min is None:
        lines.append("  Representative component slope: Not rated")
    else:
        steepest = indicators["steepest_component"]
        component_share = steepest.get("component_percentage")
        share_text = f"; {component_share:g}% of map unit" if component_share is not None else ""
        lines.append(
            f"  Representative component slope range: {slope_min:g}% to {slope_max:g}% "
            f"(maximum: {steepest['name']}{share_text}; mukey {steepest['mukey']})"
        )

    restriction = indicators.get("shallowest_restriction")
    if restriction:
        component_share = restriction.get("component_percentage")
        share_text = f"; {component_share:g}% of map unit" if component_share is not None else ""
        lines.append(
            "  Shallowest reported restrictive layer: "
            f"{restriction['kind']} at {restriction['depth_representative_cm']:g} cm "
            f"({restriction['component']}{share_text}; mukey {restriction['mukey']})"
        )
    else:
        lines.append("  Restrictive layer: None reported in the retrieved component records")

    k_min = indicators.get("surface_k_factor_min")
    k_max = indicators.get("surface_k_factor_max")
    if k_min is None:
        lines.append("  Surface-horizon erosion K factors: Not rated")
    else:
        lines.append(f"  Surface-horizon erosion K-factor range (Kf/Kw): {k_min:g} to {k_max:g}")

    attention: list[str] = []
    hydrologic_groups = indicators["hydrologic_group_estimated_acres"]
    if any(group == "D" or group.endswith("/D") for group in hydrologic_groups):
        attention.append(
            "Hydrologic group D or a dual group ending in D is reported; review runoff and infiltration assumptions."
        )
    drainage_classes = indicators["drainage_class_estimated_acres"]
    if any("poorly drained" in label.casefold() for label in drainage_classes):
        attention.append(
            "Poorly or very poorly drained soil components are reported; review drainage and seasonal wetness."
        )
    if slope_max is not None and slope_max >= 8:
        attention.append(
            f"Representative component slopes reach {slope_max:g}%; review grading and erosion-control needs."
        )
    if restriction and restriction["depth_representative_cm"] <= 150:
        attention.append(
            "A restrictive layer is reported within 150 cm; field verification may affect excavation or foundation assumptions."
        )
    if any(
        classification != "Not prime farmland" and classification != "Not rated or not available"
        for classification in indicators["farmland_classification_acres"]
    ):
        attention.append(
            "A mapped farmland classification is present; evaluate the applicable farmland review process."
        )

    lines.extend(["", "Potential Siting Attention Indicators (not suitability ratings):"])
    lines.extend(f"- {item}" for item in attention)
    if not attention:
        lines.append(
            "- No configured attention rule was triggered; this is not a finding that the site lacks soil constraints."
        )

    components_by_mapunit: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for component in data.get("components", []):
        if component["major_component"]:
            components_by_mapunit[component["mukey"]].append(component)

    lines.extend(["", f"Major Component Evidence (first {MAX_DETAIL_MAPUNITS} map units by ROI area):"])
    for mapunit in data["mapunits"][:MAX_DETAIL_MAPUNITS]:
        lines.append(
            f"- **{mapunit['symbol']} — {mapunit['name']}**: {mapunit['area_acres']:,.2f} ROI acres; "
            f"farmland class: {mapunit['farmland_classification']}"
        )
        components = components_by_mapunit.get(mapunit["mukey"], [])
        if not components:
            lines.append("  - No major-component attributes were returned.")
            continue
        for component in components:
            pct = component["component_percentage"]
            slope = component["representative_slope_pct"]
            detail = (
                f"{component['name']} ({pct:g}% of map unit"
                if pct is not None
                else f"{component['name']} (percentage unavailable"
            )
            detail += (
                f"; HSG {component['hydrologic_group']}; drainage {component['drainage_class']}"
                f"; representative slope {slope:g}%"
                if slope is not None
                else f"; HSG {component['hydrologic_group']}; drainage {component['drainage_class']}; slope not rated"
            )
            lines.append(f"  - {detail})")

    lines.extend(
        [
            "",
            "Aggregation Note: Hydrologic-group and drainage acreages multiply each map unit's clipped ROI area "
            "by NRCS component percentage. Components are not spatially located within map units, so these are "
            "approximate composition estimates rather than mapped subareas.",
            "No composite constructability or suitability score is produced.",
        ]
    )
    return "\n".join(lines + _boundary_lines(farmland=True))


def format_farmland_classification_summary(data: dict[str, Any]) -> str:
    """Format SSURGO farmland classifications by clipped map-unit acreage."""
    lines = _base_lines(data, "NRCS SSURGO Farmland Classification Screening")
    if data.get("data_unavailable"):
        lines.append(f"Status: Data unavailable — {data.get('error', 'unknown upstream error')}")
        return "\n".join(lines + _boundary_lines(farmland=True))

    classifications = data.get("classifications", {})
    if classifications:
        lines.append("Farmland Classifications:")
        for classification, values in sorted(
            classifications.items(), key=lambda item: (-item[1]["area_acres"], item[0])
        ):
            mapunit_label = "map unit" if values["mapunit_count"] == 1 else "map units"
            lines.append(
                f"- {classification}: {values['area_acres']:,.2f} acres "
                f"({values['roi_percentage']:.2f}% of ROI; {values['mapunit_count']} {mapunit_label})"
            )
    else:
        lines.append("No SSURGO farmland classifications were returned for the ROI.")

    lines.extend(["", "Map Unit Evidence:"])
    for mapunit in data.get("mapunits", [])[:MAX_DETAIL_MAPUNITS]:
        lines.append(
            f"- {mapunit['symbol']} — {mapunit['name']}: {mapunit['farmland_classification']} "
            f"({mapunit['area_acres']:,.2f} ROI acres; mukey {mapunit['mukey']})"
        )
    if len(data.get("mapunits", [])) > MAX_DETAIL_MAPUNITS or data.get("truncated"):
        lines.append("Additional map-unit evidence is omitted from this bounded summary.")
    return "\n".join(lines + _boundary_lines(farmland=True))
